import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const schemaUrl = new URL("../packages/api-client/src/generated/schema.ts", import.meta.url);

test("the isolated generated contract contains the first authenticated journey", async () => {
  const schema = await readFile(schemaUrl, "utf8");

  assert.match(schema, /This file was auto-generated by openapi-typescript/);
  assert.match(schema, /"\/api\/session"/);
  assert.match(schema, /"\/api\/auth\/login"/);
  assert.match(schema, /"\/api\/auth\/refresh"/);
  assert.match(schema, /"\/api\/auth\/logout"/);
  assert.match(schema, /"\/api\/auth\/register"/);
  assert.match(schema, /"\/api\/auth\/invitations\/\{token\}\/register"/);
  assert.match(schema, /auth_register/);
  assert.match(schema, /auth_invitation_register/);
  assert.doesNotMatch(schema, /api_auth_login/);
  assert.doesNotMatch(schema, /login_check_post/);
  assert.match(schema, /CurrentSessionResource/);
  assert.match(schema, /defaultCurrency: string/);
  assert.match(schema, /type: "ORGANIZATION" \| "SELECTED_STORES"/);
  assert.match(schema, /"\/api\/stores"/);
});
