api_platform:
    title: Zandu Sales Manager API
    version: 0.1.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/Modules/Organization/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/IdentityAccess/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/Catalog/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/Pricing/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/Inventory/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/CashManagement/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/Catalog/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/Pricing/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/Inventory/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/CashManagement/Presentation/Api'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    patch_formats:
        json:
            mime_types:
                - 'application/merge-patch+json'
                - 'application/json'
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
