api_platform:
    title: Zandu Sales Manager API
    version: 0.1.0
    enable_swagger_ui: false
    enable_re_doc: false
    enable_scalar: false
    mapping:
        paths:
            - '%kernel.project_dir%/src/Modules/Organization/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/IdentityAccess/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/Catalog/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/Pricing/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/Inventory/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/InventoryCosting/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/CashManagement/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/Sales/Presentation/Api'
            - '%kernel.project_dir%/src/Modules/Purchasing/Presentation/Api'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    patch_formats:
        json:
            mime_types:
                - 'application/merge-patch+json'
                - 'application/json'
    collection:
        pagination:
            page_parameter_name: page
            items_per_page_parameter_name: limit
    defaults:
        stateless: true
        pagination_enabled: true
        pagination_items_per_page: 30
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: '%app.api.pagination_maximum_items_per_page%'
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
